--- #YAML:1.0
name:               GOBO
version:            0.02
abstract:           Perl library for GO and OBO
author:
    - Chris Mungall <cjm@fruitfly.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AmiGO::Model::Graph:  0
    DateTime::Format::ISO8601:  0
    DBIx::Class:          0
    Graph:                0
    List::MoreUtils:      0
    Lucene:               0
    Moose:                0
    RDF::Redland:         0
    Set::Object:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
